Drop support for Python 2.7, 3.5, 3.6.
zopefoundation/AccessControl pull request #137
Opened 2022-12-20 15:50 UTC by icemac

2022-12-21 07:36 UTC, d-maurer requested changes
Apparently, `github` still tries to run Python 2.7 tests.

2022-12-21 08:52 UTC, dataflake commented
> Apparently, `github` still tries to run Python 2.7 tests.

No it does not. The branch protection rules for the master branch still expected to see those tests, that's all. I have removed them from the rule.

2022-12-21 09:02 UTC, dataflake approved these changes

2022-12-21 09:28 UTC, d-maurer approved these changes

2022-12-23 08:39 UTC, icemac commented
Thank you for reviewing this PR. 😃

2022-12-23 08:39 UTC, merged